### ISSUE TITLE
Feature Request: Generate Entity framework `ValueConverter`

### ISSUE THREAD

**Issue by xshaheen** [altasoft/DomainPrimitives#12]
I think it will be helpful to add `Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter` for each domain primitive

**Comment by temonk** [comment]
@xshaheen Thanks for the suggestion. We've added support for ValueConverters, available in version **4.1.0**. Please refer to the [Value Converters Example](https://github.com/altasoft/DomainPrimitives/blob/main/EntityFrameworkCoreExample.md).

**Comment by xshaheen** [comment]
Great thank you for the quick response
