### ISSUE TITLE
Keeps generating swagger file,  even if putting false in csproj

### ISSUE THREAD

**Issue by ignatandrei** [altasoft/DomainPrimitives#2]
I have tried to add
```xml
	<PropertyGroup>
		<DomainPrimitiveGenerator_GenerateJsonConverters>false</DomainPrimitiveGenerator_GenerateJsonConverters>
		<DomainPrimitiveGenerator_GenerateTypeConverters>false</DomainPrimitiveGenerator_GenerateTypeConverters>
		<DomainPrimitiveGenerator_GenerateSwaggerConverters>false</DomainPrimitiveGenerator_GenerateSwaggerConverters>
	</PropertyGroup>
```
to the generator in order to not generate data for Swagger. However this version
```xml
<ItemGroup>
	<PackageReference Include="AltaSoft.DomainPrimitives.Abstractions" Version="1.0.3" />
	<PackageReference Include="AltaSoft.DomainPrimitives.Generator" Version="1.0.3" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all" ExcludeAssets="runtime" />
</ItemGroup>
<PropertyGroup>
	<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
	<CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)\GX</CompilerGeneratedFilesOutputPath>
</PropertyGroup>
	```
keeps generating files for swagger. Attached the project  - please see folder obj/GX
[DomainPrimitives.zip](https://github.com/altasoft/DomainPrimitives/files/13897845/DomainPrimitives.zip)

( I have tested because I wanted to add to my list of RSCG, https://ignatandrei.github.io/RSCG_Examples/v2/docs/List-of-RSCG )

**Comment by temonk** [comment]
You are missing ItemGroup section to pass PropertyGroup items to the generator. Please try to add this to the .csproj file and everything should work fine.  
 <ItemGroup>
    <CompilerVisibleProperty Include="DomainPrimitiveGenerator_GenerateJsonConverters" />
    <CompilerVisibleProperty Include="DomainPrimitiveGenerator_GenerateTypeConverters" />
    <CompilerVisibleProperty Include="DomainPrimitiveGenerator_GenerateSwaggerConverters" />
  </ItemGroup>

Also, if you just want to disable swagger you can only include DomainPrimitiveGenerator_GenerateSwaggerConverters and ignore the rest as they will be automatically generated.

**Comment by temonk** [comment]
Here is an example
```xml
<ItemGroup>
	<PackageReference Include="AltaSoft.DomainPrimitives.Abstractions" Version="1.0.3" />
	<PackageReference Include="AltaSoft.DomainPrimitives.Generator" Version="1.0.3" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all" ExcludeAssets="runtime" />
</ItemGroup>

<PropertyGroup>
<DomainPrimitiveGenerator_GenerateSwaggerConverters>false</DomainPrimitiveGenerator_GenerateSwaggerConverters>
</PropertyGroup>

<ItemGroup>
<CompilerVisibleProperty Include="DomainPrimitiveGenerator_GenerateSwaggerConverters" />
</ItemGroup>
```
... rest of your code

**Comment by ignatandrei** [comment]
Thanks 
Done  -  link at https://ignatandrei.github.io/RSCG_Examples/v2/docs/DomainPrimitives
